name: workflows
permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches:
      - main
  #  paths-ignore:
  #    - '.github/workflows/*'
  # pull_request:
  #  branches:
  #    - main
  #  types:
  #    - opened

jobs: #Commandes à exécuter
  test: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Test is OK"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build is Ok"
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Code 
        uses: actions/checkout@v4
      #- name: Install java
      #  uses: actions/setup-java@v4
      #  with:
      #    distribution: 'oracle'
      #    java-version: '17'
      #    cache: maven
      #- name: Execute test
      #  run: mvn test
      - name: deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.edirenaud.site
          username: {{ secrets.USERNAME}}
          password: {{ secrets.PASSWORD}}
        #env:
        #  ACCESS_TOKEN: {{ secrets.ACCESS_TOKEN}}
